### ISSUE TITLE
I2C instead or serial connected device

### ISSUE THREAD

**Issue by RolandPenning** [Jaeyoung-Lim/rosppm#3]
Hello Jaeyoung-Lim,

Would be nice to see the Arduino connected as a device on the I2C-bus (multi device bus) instead of the serial-bus (single device bus), this way the serial bus stays available.

Regards,
Roland Penning

**Comment by Jaeyoung-Lim** [comment]
Thank you for your feedback :)

However do you mean this by controlling the arduino not from a ROS running PC but another device?

**Comment by RolandPenning** [comment]
No,
I mean not using rosserial /dev/tty01 to connect to a Arduino as node and
losing a serial device-adress on a board like the Beaglebone or Rasberry
Pi. Connecting an Arduino node on the I2C-bus (with a lot of free
device-adresses) to ROS with publishing and/or subscribing functionality.

Regards,
Roland Penning

2016-12-13 16:46 GMT+01:00 JaeyoungLim <notifications@github.com>:

**Comment by Jaeyoung-Lim** [comment]
closed as this issue is stale
