### ISSUE TITLE
rosppm/ppm_io.h missing

### ISSUE THREAD

**Issue by charles-blouin** [Jaeyoung-Lim/rosppm#6]
Hi Jaeyoung,

First, thanks for making the code available!

I may be misunderstanding part of the install process, but when I try to flash the rosppm_arduino.ino on an arduino using the arduino IDE, get at missing file error:
rosppm/ppm_io.h missing

Is this file with another library? The installation instruction say:

catkin_make --pkg usb2ppm_ros

I checked your usb2ppm package, and I do not see the ppm_io.h file.

Thanks! I would much prefer to use your code over rewriting the same thing :)

**Comment by charles-blouin** [comment]
Found it!

I was not familliar with ros serial. You simply need to run the commands:

  cd <sketchbook>/libraries
  rm -rf ros_lib
  rosrun rosserial_arduino make_libraries.py .

To regenerate your arduino libraries.

**Comment by Jaeyoung-Lim** [comment]
@charles-blouin That is great to hear

**Comment by Jaeyoung-Lim** [comment]
@charles-blouin If you are planning to send commands to the transmitter using rosppm,
could you the master branch?

I have a fix which now should be working properly

**Comment by charles-blouin** [comment]
Thanks, I will try. The signal I was getting on the oscilloscope did not look right and that part of the code seemed like it was the problem. I will report on Monday if I have problems, thanks!
